### ISSUE TITLE
angel build/deploy fails on version 0.2.x

### ISSUE THREAD

**Issue by emdeha** [outbounder/organic-stem-devtools#1]
A bootstrapped project can't be built because on `angel build`, the `node.os` module fails with

```
/home/emdeha/project/node_modules/node.os/src/index.js:7
    let os;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/emdeha/work/hobis/node_modules/organic-stem-devtools/lib/os.js:2:24)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Node version: 5.6.0

I'll provide more info if needed! Thanks :bow:

**Comment by outbounder** [comment]
yeap @emdeha :bow: for the spot.

Seems that the issue comes from node.os 1.2.0 which has been released just 2 days ago, using v1.1.1 should do the trick

**Comment by emdeha** [comment]
Thanks @outbounder. Closing the issue.

**Comment by yeliex** [comment]
the `1.2.0` version added some props for `wechat`and `electron`,and refacted with es6, they are not necessary for most users
